### ISSUE TITLE
Playlist URL format wrong.

### ISSUE THREAD

**Issue by marvoh** [svbnet/Athame#80] opened 2017-10-23 02:56 UTC
I keep getting the attached error when I try to add tidal playlist for download on both 0.4.4 and 0.4.5 versions.

![athame](https://user-images.githubusercontent.com/5451142/31870496-f78d2378-b7b6-11e7-997a-0c101711dc83.png)

**Comment by SchwanzusLongus** [comment] 2017-10-23 04:06
Got the same issue. There seems something to be wrong in 0.4.5.
You have to delete config files **AppData\Roaming\Athame** and start 0.4.4. again.
This should bring 0.4.4. to work.

**Comment by svbnet** [comment] 2017-11-12 01:53
Can you please post the playlist URL below?

**Comment by svbnet** [comment] 2017-11-12 05:05
Duplicate of #74

**Closed by svbnet** 2017-11-12 05:05 UTC

**Comment by aowzone** [comment] 2017-12-09 22:44
Built latest athame from master (2017-12-09) and TIDAL playlist URL is now parsed and downloaded, with one caveat.  Must check the "use same settings as album" for the download location.  If you try to set a custom download location, all files will download, but they overwrite themselves with  path/to/name of playlist/"name of the playlist.flac" and the only file you get in the end is the last song in the list.

Great progress, just a tiny bug to squash now!
