### ISSUE TITLE
Trying to download Tidal Albums without a cover art picture crashes Athame

### ISSUE THREAD

**Issue by tboned-car** [svbnet/Athame#37] opened 2017-06-30 23:11 UTC
What is your OS version?
Windows 10 LTSB 1607 with all updates installed as of June 30 2017

Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file.
Yes

Have you ensured you are using the latest version?
Yes

Can you play back the track or collection on the web?
Yes

Some example albums that reproduces this: https://listen.tidal.com/album/70828176 https://listen.tidal.com/album/70828124

Log: https://pastebin.com/raw/xu3EXqUD

**Comment by FatKiwi** [comment] 2017-07-01 00:10
Same issue: https://github.com/svbnet/Athame/issues/32
If this happens to you, then the problem is definitely the artwork missing. So another confirmed crash. Thanks

**Comment by svbnet** [comment] 2017-07-01 02:26
Should be fixed in next release.

**Closed by svbnet** 2017-07-01 02:26 UTC
