### ISSUE TITLE
Help please! An error occurred while downloading this track: https://tidal.com/track/22597999

### ISSUE THREAD

**Issue by Eduardo44** [svbnet/Athame#86] opened 2017-11-03 18:05 UTC
-

If you've found a bug, please answer these questions:
What is your OS version?
Windows 10
Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file.
Have you ensured you are using the latest version?
Yes
Can you play back the track or collection on the web?
Yes
![tidal error](https://user-images.githubusercontent.com/33356919/32389183-fbe37686-c097-11e7-84f5-58eb71b58fc7.png)

**Comment by fabriccioguzman** [comment] 2017-11-03 20:27
Tienes que cambiar la ubicacion de descarga en menu en config y te aparece una opcion para cambiarla

**Comment by svbnet** [comment] 2017-11-12 05:06
Duplicate of #85

**Closed by svbnet** 2017-11-12 05:06 UTC
Labels: bug

**Comment by Alternativshik6** [comment] 2018-05-28 05:27
Help please! An error occurred while downloading this track. The problem with Google Play. With Tidal there are no problems
![default](https://user-images.githubusercontent.com/39688328/40598500-afea54c4-6250-11e8-91f9-bfac7e283db0.jpg)

**Comment by FatKiwi** [comment] 2018-05-28 07:37
Mass spam. #151
