### ISSUE TITLE
Can't open the .exe

### ISSUE THREAD

**Issue by hjtech** [svbnet/Athame#20] opened 2017-05-10 15:58 UTC
Tried on Windows 10 and Windows Server Essentials. Using version 0.4.2:

> [2017-05-10T08:55:24.9669235-07:00] [Fatal] AppDomain: Unhandled exception
NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Athame.Plugin.PluginManager.<>c.<LoadAll>b__19_0(String dllPath)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Athame.Plugin.PluginManager.LoadAll()
   at Athame.UI.MainForm..ctor()
   at Athame.Program.Main()

**Comment by alfablac** [comment] 2017-05-10 21:48
Right-click the .exe and .dll files and check the box "Unlock" and hit OK.
It seems there's a security option between a compiled app and .NET.
I tried to fix it editing some files on the source code but it didn't fix it. 
No idea what's causing this.

**Comment by svbnet** [comment] 2017-05-11 08:57
I think it's caused by the plugin assemblies or supporting assemblies having the "downloaded from an unknown source" attribute. In any case you can just right-click the .exe and .dll files and click "Unblock" in the properties window. This should be fixed in a new release.

**Closed by svbnet** 2017-05-11 08:57 UTC
