### ISSUE TITLE
some tidal music still can't download when no release date

### ISSUE THREAD

**Issue by littlealone100** [svbnet/Athame#77] opened 2017-10-19 19:14 UTC
Some tidal music still can't download, such as these tidal album id: 57608727, 57608707.

When I add url, it is said "The Provided URL maybe Invalid or unsuported".

detail: error converting value {null} to type "System.DateTime"

**Comment by fabriccioguzman** [comment] 2017-10-19 23:04
Verify that your account is hifi and verifies that this music is available in the region that you used vpn

And it verifies that eras folder pa athame that is in app roaming app

**Comment by littlealone100** [comment] 2017-10-20 06:02
> Verify that your account is hifi and verifies that this music is available in the region that you used vpn. And it verifies that eras folder pa athame that is in app roaming app

My account is hifi and I can stream that album. I also can download other album.
But these album really can't download.
tidal album id: 57608727, 57608707

**Comment by Hermit121** [comment] 2017-10-20 08:16
Hey I also cannot download anything anymore. As soon as I close Athame and open it again it says that the URL might be wrong. If I clear the folder in appdata and restart it, I can download, but after closing it, it doesnt download anymore and stops on the URL

**Comment by Hermit121** [comment] 2017-10-20 08:22
I think I found my error, its {ServiceName}

**Comment by jonaaa20** [comment] 2017-10-20 14:43
This may be not working because of Japanese name?

**Comment by littlealone100** [comment] 2017-10-20 19:38
> This may be not working because of Japanese name?

I don't think so. 
Because athame show this info: error converting value {null} to type "System.DateTime".
These albums don't have release date on tidal. I think it is the reason.

**Comment by fabriccioguzman** [comment] 2017-10-21 01:43
the only way is for svbnet to have athame download the file directly from the tidal web player that is generated through a link that appears in fiddler and that athame decrypts it and writes the data and cover
and not using the tidal api to get the flac

ONLY FOR THIS TYPE OF CASE

**Comment by UserForTheOnlyTopic** [comment] 2017-10-21 15:26
@littlealone100 and other:
there is no a problem with downloading these albums. The problem is on your side, i assume it can be with your OS's coding or something like, at most in the last Athame. If you still think the problem is with Athame, try to use more older version (i use a bit older version, not 4.5).

**Comment by littlealone100** [comment] 2017-10-21 16:18
> @littlealone100 and other:
there is no a problem with downloading these albums. The problem is on your side, i assume it can be with your OS's coding or something like, at most in the last Athame. If you still think the problem is with Athame, try to use more older version (i use a bit older version, not 4.5).

Thanks. It is worked by Athame 4.3. 
But not worked by Athame 4.4 or 4.5.

**Closed** 2017-10-21 16:28 UTC
