### ISSUE TITLE
I get this error on a few tracks in the release version

### ISSUE THREAD

**Issue by turismo444** [svbnet/Athame#9] opened 2017-04-11 14:49 UTC
this program lets a dream come true =) keep it up!
i get this on a few tracks
![unbenannt](https://cloud.githubusercontent.com/assets/17822754/24915109/9097bcd8-1ed6-11e7-92df-98651d28dc30.png)

**Comment by smiba** [comment] 2017-04-11 15:47
If I'm not mistaken this happens because the song was not available in FLAC format but only MP3, This causes tidal to serve Athame a MP3 while it expected a FLAC

I already reported this issue and showed a (temporary) fix in #1, however it was not approved. I'm still haven't had time to implement the proper solution as the developer suggested (checking the magic bytes of the downloaded file) though

I'll see if I can apply my fix to this current version, give me a moment

**Comment by turismo444** [comment] 2017-04-11 15:57
thaanx for the fast reply!

i understand.. i can imagine that it is quite tricky to solve that!

but great work tho, really :O

________________________________
Von: Bart S. <notifications@github.com>
Gesendet: Dienstag, 11. April 2017 17:47
An: svbnet/Athame
Cc: turismo444; Author
Betreff: Re: [svbnet/Athame] I get this error on a few tracks in the release version (#9)


If I'm not mistaken this happens because the song was not available in FLAC format but only MP3, This causes tidal to serve Athame a MP3 while it expected a FLAC

I already reported this issue and showed a (temporary) fix in #1<https://github.com/svbnet/Athame/pull/1>, however it was not approved. I'm still haven't had time to implement the proper solution as the developer suggested (checking the magic bytes of the downloaded file) though

I'll see if I can apply my fix to this current version, give me a moment

**Comment by smiba** [comment] 2017-04-11 20:17
I found the issue but its actually a bit different from last time

The purposed fix is at #11 in my repo 1608310

**Comment by svbnet** [comment] 2017-04-12 13:08
I've been working on this issue, which will be fixed since the service now returns a MIME type, bitrate, and URL as opposed to just a URL. 

The cause of _this_ issue is because TagLib tries to detect the MIME type from the extension (it shouldn't but it does), which causes it to load the incorrect parser and crash. Hopefully in the next release (things have been progressing slowly but it will come), this issue should be wholly resolved.

**Closed by svbnet** 2017-04-12 13:08 UTC
